// swift-tools-version: 6.1
// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.
//
// Mirrors PrimJS.podspec; keep the two in sync.
//
//   PrimJS/quickjs + PrimJS/log      -> PrimJS
//   PrimJS/quickjs_debugger          -> `Debugger` trait (PrimJSInspector)
//   PrimJS/napi/{core,env,quickjs}   -> PrimJSNAPI
//   PrimJS/napi/jsc                  -> PrimJSNAPIJSC
//   PrimJS/napi/adapter              -> PrimJSNAPIAdapter
//
// Public headers live in swiftpm/headers/<Target>/, generated by
// tools/ios_tools/generate_spm_headers.py with the CocoaPods layout so include
// paths are the same for both package managers. arm64 only, like the podspec.

import PackageDescription

// GCC_PREPROCESSOR_DEFINITIONS of the pod target and the `quickjs` subspec.
// They change struct layouts in quickjs-inner.h, so every target uses the
// same list.
let podDefines: [CXXSetting] = [
  .define("OS_IOS", to: "1"),
  .define("ENABLE_CODECACHE"),
  .define("ENABLE_VIRTUAL_STACK", to: "1"),
  .define("ENABLE_PRIMJS_SNAPSHOT"),
  .define("ENABLE_COMPATIBLE_MM"),
  .define("ENABLE_LEPUSNG"),
  .define("LYNX_SIMPLIFY", to: "0"),
  // Like the quickjs_debugger subspec, this switches the whole engine.
  .define("ENABLE_QUICKJS_DEBUGGER", .when(traits: ["Debugger"])),
]

let podHeaderSearchPaths: [CXXSetting] = [
  .headerSearchPath("src"),
  .headerSearchPath("src/interpreter"),
]

// The napi sources include their headers by bare name.
let napiHeaderSearchPaths: [CXXSetting] = [
  .headerSearchPath("src/napi"),
  .headerSearchPath("src/napi/common"),
  .headerSearchPath("src/napi/env"),
  .headerSearchPath("src/napi/quickjs"),
  .headerSearchPath("src/napi/adapter"),
]

let package = Package(
  name: "PrimJS",
  platforms: [
    .iOS(.v12),
    // Same configuration as iOS; used for `swift build` / `swift test`.
    .macOS(.v10_15),
  ],
  products: [
    .library(name: "PrimJS", targets: ["PrimJS"]),
    .library(name: "PrimJSNAPI", targets: ["PrimJSNAPI"]),
    .library(name: "PrimJSNAPIJSC", targets: ["PrimJSNAPIJSC"]),
    .library(name: "PrimJSNAPIAdapter", targets: ["PrimJSNAPIAdapter"]),
  ],
  traits: [
    .trait(
      name: "Debugger",
      description:
        "Build the engine with the Chrome DevTools Protocol debugger "
        + "(PrimJS/quickjs_debugger). Changes the engine ABI."),
  ],
  targets: [
    .target(
      name: "PrimJS",
      dependencies: [
        .target(name: "PrimJSInspector", condition: .when(traits: ["Debugger"]))
      ],
      path: ".",
      exclude: [
        "src/gc/BUILD.gn",
        "src/interpreter/quickjs/BUILD.gn",
      ],
      sources: [
        "src/gc",
        "src/interpreter/quickjs",
        // embedded.S / embedded-inspector.S guard on ENABLE_QUICKJS_DEBUGGER.
        "src/interpreter/primjs/ios",
        "src/basic/log",
      ],
      publicHeadersPath: "swiftpm/headers/PrimJS",
      cxxSettings: podDefines + podHeaderSearchPaths
    ),

    // Always built with the debugger ABI; linked only under the trait. The
    // engine and the inspector reference each other; the linker resolves it.
    .target(
      name: "PrimJSInspector",
      path: ".",
      exclude: [
        "src/inspector/BUILD.gn"
      ],
      sources: [
        "src/inspector"
      ],
      publicHeadersPath: "swiftpm/headers/PrimJSInspector",
      cxxSettings: podDefines + podHeaderSearchPaths + [
        .define("ENABLE_QUICKJS_DEBUGGER")
      ]
    ),

    .target(
      name: "PrimJSNAPI",
      dependencies: ["PrimJS"],
      path: ".",
      exclude: [
        "src/napi/common/BUILD.gn",
        "src/napi/env/BUILD.gn",
        "src/napi/quickjs/BUILD.gn",
      ],
      sources: [
        // The podspec glob src/napi/*.{h,cc} is non-recursive.
        "src/napi/napi.cc",
        "src/napi/napi_module.cc",
        "src/napi/common",
        "src/napi/env",
        "src/napi/quickjs",
      ],
      publicHeadersPath: "swiftpm/headers/PrimJSNAPI",
      cxxSettings: podDefines + podHeaderSearchPaths + napiHeaderSearchPaths
    ),

    .target(
      name: "PrimJSNAPIJSC",
      dependencies: ["PrimJSNAPI", "PrimJS"],
      path: ".",
      exclude: [
        "src/napi/jsc/BUILD.gn"
      ],
      sources: [
        "src/napi/jsc"
      ],
      publicHeadersPath: "swiftpm/headers/PrimJSNAPIJSC",
      cxxSettings: podDefines + podHeaderSearchPaths + napiHeaderSearchPaths + [
        .define("JSC_OBJC_API_ENABLED", to: "0")
      ],
      linkerSettings: [
        .linkedFramework("JavaScriptCore")
      ]
    ),

    .target(
      name: "PrimJSNAPIAdapter",
      dependencies: ["PrimJSNAPI"],
      path: ".",
      sources: [
        // weak_napi_host_injector.cc belongs to the LynxWeakNodeAPI pod.
        "src/napi/adapter/js_native_api_adapter.cc",
        "src/napi/adapter/weak_napi_host_generator.cc",
      ],
      publicHeadersPath: "swiftpm/headers/PrimJSNAPIAdapter",
      cxxSettings: podDefines + podHeaderSearchPaths + napiHeaderSearchPaths
    ),

    .testTarget(
      name: "PrimJSTests",
      dependencies: ["PrimJS", "PrimJSNAPI"],
      path: "swiftpm/Tests/PrimJSTests",
      cxxSettings: [
        // Users of the Node-API headers must define this themselves.
        .define("ENABLE_CODECACHE")
      ],
      linkerSettings: [
        // Only linked implicitly for Swift test targets.
        .linkedFramework("Foundation"),
        .linkedFramework("XCTest"),
      ]
    ),

    .testTarget(
      name: "PrimJSSwiftTests",
      dependencies: ["PrimJS"],
      path: "swiftpm/Tests/PrimJSSwiftTests"
    ),
  ],
  cxxLanguageStandard: .gnucxx17
)
