# Copyright 2024 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("//Primjs.gni")
primjs_source_set("gc") {
  sources = [
    "collector.cc",
    "collector_ms.cc",
    "global-handles.cc",
    "logger.cc",
    "mem_map.cc",
    "mrt_bitmap.cc",
    "page_group.cc",
    "page_map.cc",
    "qjsvaluevalue-space.cc",
    "ros_allocator.cc",
    "space.cc",
    "gc_marking.cc",
    "gc_tracer.cc",
    "thread_pool.cc"
  ]
}
