ARTIFACT_GROUP=org.lynxsdk.lynx
ARTIFACT_NAME=primjsWasm
DESCRIPTION=PrimjsWasm
REPOSITORY_URL=https://github.com/lynx-family/primjs
REPOSITORY_SSH_URL=github.com/lynx-family/primjs.git
DEVELOPER_NAME=lynx
DEVELOPER_EMAIL=lynx.authors@gmail.com

# Build options
enable_debugging=false
js_engine=quickjs
