# Copyright 2024 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("//Primjs.gni")
import("//testing/test.gni")

config("config") {
  include_dirs = [
    ".",
    "../../../src/interpreter",
    "../../../src/inspector",
    "${root_gen_dir}",
  ]
}

unittest_set("heap_tests") {
  public_configs = [ ":config" ]
  public_deps = [ "../../../src:quickjs_lib" ]

  sources = [
    "test_base.cc",
    "test_heap.cc",
  ]
  cflags = [ "-Wno-c99-designator" ]
}

unit_test("heap_unittest") {
  testonly = true

  sources = []

  public_deps = [ ":heap_tests" ]
}
