name: ci-test-harmony

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test-harmony-ci:
    runs-on: lynx-dind
    container: 
      image: ghcr.io/lynx-family/harmony:5.0.9.310
      # options: --cap-add=NET_ADMIN  # 添加网络管理权限
      # options: --network=host
      credentials:
        username: lynx-family
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Show env
        run: |
          env
      # - name: Download Source
      #   uses: actions/checkout@v4.2.2
      - name: Show file system
        run: |
          ls -al
      - name: debug
        shell: bash
        run: |
          sleep infinity
        # cat /proc/1/cgroup | grep docker
        # ls -l /var/run/docker.sock
      # - name: Assemble HAP
      #   run: |
      #     cd harmony && hvigorw assembleApp 

  test-harmony-ci-custom:
    runs-on: lynx-custom-dind
    container: 
      image: ghcr.io/lynx-family/harmony:5.0.9.310
      options: --cap-add=NET_ADMIN  # 添加网络管理权限
      # options: --network=host
      credentials:
        username: lynx-family
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Show env
        run: |
          env
      # - name: Download Source
      #   uses: actions/checkout@v4.2.2
      - name: Show file system
        run: |
          ls -al
      - name: debug
        shell: bash
        run: |
          sleep infinity
        # cat /proc/1/cgroup | grep docker
        # ls -l /var/run/docker.sock
      # - name: Assemble HAP
      #   run: |
      #     cd harmony && hvigorw assembleApp
